[package]
name = "phetch"
version = "0.1.5"
authors = ["dvkt <c@dvkt.io>"]
license = "MIT"
edition = "2018"
description = "quick lil gopher client"
readme = "README.md"
repository = "https://github.com/dvkt/phetch"
keywords = ["gopher", "tui", "terminal", "cli"]
categories = ["command-line-utilities"]
exclude = [
    "img/*"
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
opt-level = 'z'  # Optimize for size.

[dependencies]
termion = "1.5.3"
