[package]
name = "phetch"
version = "0.1.1"
authors = ["dvkt <c@dvkt.io>"]
license = "MIT"
description = "a terminal gopher client designed to help you quickly navigate the gophersphere"
repository = "https://github.com/dvkt/phetch"
keywords = ["gopher", "tui", "terminal"]
exclude = [
    "img/*"
]

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
opt-level = 'z'  # Optimize for size.

[dependencies]
termion = "1.5.3"
